# Generated by Django 5.1.7 on 2025-04-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='익명', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
